-- Script para criação das tabelas do Sistema ERP Comercial

CREATE TABLE Cliente (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE,
    telefone VARCHAR2(20),
    data_cadastro DATE DEFAULT SYSDATE,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE Endereco (
    endereco_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    logradouro VARCHAR2(100) NOT NULL,
    numero VARCHAR2(20),
    complemento VARCHAR2(50),
    bairro VARCHAR2(50),
    cidade VARCHAR2(50) NOT NULL,
    estado VARCHAR2(2) NOT NULL,
    cep VARCHAR2(10) NOT NULL,
    tipo_endereco VARCHAR2(20) CHECK (tipo_endereco IN ('Residencial', 'Comercial', 'Entrega'))
);

CREATE TABLE Cargo (
    cargo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cargo VARCHAR2(50) UNIQUE NOT NULL,
    descricao VARCHAR2(200)
);

CREATE TABLE Funcionario (
    funcionario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE,
    telefone VARCHAR2(20),
    data_contratacao DATE DEFAULT SYSDATE,
    cargo_id NUMBER NOT NULL
);

CREATE TABLE Fornecedor (
    fornecedor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fantasia VARCHAR2(100) NOT NULL,
    razao_social VARCHAR2(100) UNIQUE NOT NULL,
    cnpj VARCHAR2(18) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE,
    telefone VARCHAR2(20)
);

CREATE TABLE Categoria (
    categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_categoria VARCHAR2(50) UNIQUE NOT NULL,
    descricao VARCHAR2(200)
);

CREATE TABLE Produto (
    produto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(500),
    preco_unitario NUMBER(10, 2) NOT NULL,
    estoque NUMBER(10) DEFAULT 0,
    categoria_id NUMBER NOT NULL,
    fornecedor_id NUMBER NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE Compra (
    compra_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id NUMBER NOT NULL,
    funcionario_id NUMBER NOT NULL,
    data_compra DATE DEFAULT SYSDATE,
    valor_total NUMBER(10, 2) DEFAULT 0
);

CREATE TABLE ItemCompra (
    item_compra_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id NUMBER NOT NULL,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER(10) NOT NULL,
    preco_unitario NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL
);

CREATE TABLE Venda (
    venda_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    funcionario_id NUMBER NOT NULL,
    data_venda DATE DEFAULT SYSDATE,
    valor_total NUMBER(10, 2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'Concluida' CHECK (status IN ('Concluida', 'Cancelada', 'Pendente'))
);

CREATE TABLE ItemVenda (
    item_venda_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id NUMBER NOT NULL,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER(10) NOT NULL,
    preco_unitario NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL
);

CREATE TABLE Pagamento (
    pagamento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id NUMBER NOT NULL,
    data_pagamento DATE DEFAULT SYSDATE,
    valor_pagamento NUMBER(10, 2) NOT NULL,
    metodo_pagamento VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Aprovado' CHECK (status IN ('Aprovado', 'Pendente', 'Recusado'))
);

CREATE TABLE Perfil (
    perfil_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_perfil VARCHAR2(50) UNIQUE NOT NULL,
    descricao VARCHAR2(200)
);

CREATE TABLE Usuario (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id NUMBER UNIQUE NOT NULL,
    username VARCHAR2(50) UNIQUE NOT NULL,
    senha VARCHAR2(100) NOT NULL,
    perfil_id NUMBER NOT NULL,
    data_criacao DATE DEFAULT SYSDATE,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE Auditoria (
    auditoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_afetada VARCHAR2(50) NOT NULL,
    coluna_afetada VARCHAR2(50),
    id_registro_afetado NUMBER NOT NULL,
    acao VARCHAR2(20) NOT NULL,
    valor_antigo VARCHAR2(4000),
    valor_novo VARCHAR2(4000),
    data_alteracao TIMESTAMP DEFAULT SYSTIMESTAMP,
    usuario_id NUMBER
);
